### ISSUE TITLE
bug: Can't get compiler working with Next.js

### ISSUE THREAD

**Issue by enjoijkee** [aidenybai/million#448]
**Describe the bug**
I'm using React + Next.js (used `create-next-app` to create a project). I've tried different approaches to install the Million compiler but I'm always getting:
```
Error: See http://million.dev/docs/install to install the compiler.
    at file:///.../node_modules/million/dist/chunks/block.mjs:4:9
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15) {
  digest: undefined
```

It happens even if I totally copy-paste next.config.mjs from the documentation:
```
import million from 'million/compiler';
 
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};
 
export default million.next(nextConfig);
```

Tried to wrap my previous config into `million.next()` as well:
<img width="1366" alt="Screenshot 2023-06-22 at 18 14 31" src="https://github.com/aidenybai/million/assets/9976361/c6c3faea-0109-4af1-9015-3906ae19db79">

React 18.2.0, Next 13.4.3, Million tried 2.4.8.beta-3 and 2.4.7.

**Comment by enjoijkee** [comment]
I used Million in two components:

Table component:
```
<For each={data}>
  {(row, index) => (
    <>
      {/* @ts-expect-error Server Component */}
      <RowBlock key={`tr-${index}`} row={row} columns={columns} onRowClick={onRowClick} />
    </>
  )}
</For>
```

RowBlock:
```
import { block } from 'million';
import { Column, Row } from '@/types/table';
import Cell from './Cell';
import { TD } from './Content';
import { styled } from '@/stitches';

type Props = {
  row: Row;
  columns: Column[];
  onRowClick?: (row: Row) => void;
};

const RowBlock = ({ row, columns, onRowClick }: Props) => {
  return (
    <TR clickable={!!onRowClick} onClick={() => (onRowClick ? onRowClick(row) : undefined)}>
      {columns.map((column) => (
        <Cell key={`td-${column.title}`} row={row} column={column} />
      ))}
    </TR>
  );
};

export default block(RowBlock);

const TR = styled('tr', {
  variants: {
    clickable: {
      true: {
        cursor: 'pointer',
        transition: '$default',
        [`&:hover ${TD}`]: {
          bgc: '$componentHoverBg',
        },
      },
    },
  },
});
```

**Comment by aidenybai** [comment]
I see a couple issues that should be fixed:

`export default block(RowBlock);` is not recognized usage yet. I recommend wrapping it inline:

```js
const RowBlock = block(({ row, columns, onRowClick }: Props) => {
  return (
    <TR clickable={!!onRowClick} onClick={() => (onRowClick ? onRowClick(row) : undefined)}>
      {columns.map((column) => (
        <Cell key={`td-${column.title}`} row={row} column={column} />
      ))}
    </TR>
  );
});
```

Also, blocks are not supported as server components. `"use client";` is required in this case, as with server components, there would be no performance benefit anyway.

**Comment by enjoijkee** [comment]
Thank you for response!
I tried this wrapping as well and it didn't affect the problem. Anyway I've edited as you suggested, thanks. However I'm getting the same error despite all these fixes. Where should I add `"use client"` directive? Now I've added it in `RowBlock` and its parent component. Should it be in some another place?
Am I supposed to get the error about compiler although it might be a problem in my incorrect usage?

**Comment by aidenybai** [comment]
@enjoijkee I'm not actually super sure because I haven't played around with app dir enough, but from what I understand you might want to at least use the directive where the block is used. What I would do here is to add "use client" everywhere and incrementally remove it until you hit an error.

Better Error messages with RSC is something we are still working on. This report is helpful, however.

**Comment by enjoijkee** [comment]
Welp, I've added the directive literally everywhere and the error is still here. I tend to think the problem is somewhere deeper, maybe in Next configuration, but I can't get it work even with the default config from your documentation.

**Comment by aidenybai** [comment]
Hmm, interesting. Mind joining https://million.dev/chat to debug this quicker? @enjoijkee

**Comment by aidenybai** [comment]
wait a sec, i think you're importing from the wrong place, it's supposed to be `million/react` @enjoijkee

**Comment by enjoijkee** [comment]
@aidenybai you're right, edited import to `import { block } from 'million/react';` but it's still there unfortunately

**Comment by enjoijkee** [comment]
So to be clear now, that's what I have at the moment:

package.json
```
{
  "name": "frontend",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    // default scripts
  },
  "dependencies": {
    "@apollo/client": "^3.7.14",
    "@auth0/nextjs-auth0": "^2.6.0",
    // Radix stuff
    "graphql": "^16.6.0",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "million": "2.4.7",
    "next": "13.4.3",
    "next-images": "^1.8.5",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-wrap-balancer": "^0.5.0"
  },
  "devDependencies": {
    "@types/graphql": "14.5.0",
    "@types/lodash": "^4.14.194",
    "@types/moment": "^2.13.0",
    "@types/node": "^20.2.3",
    "@types/react": "^18.2.7",
    "@types/react-dom": "^18.2.4",
    "eslint": "8.41.0",
    "eslint-config-next": "13.4.3",
    "typescript": "5.0.4"
  }
}
```

next.config.mjs
```
import million from 'million/compiler';

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};

export default million.next(nextConfig);
```

TableContent.tsx
```
'use client';

import { For } from 'million/react';
import RowBlock from './Row';
import { Column, Row } from '@/types/table';
import { styled } from '@/stitches';

interface Props {
  data: Row[];
  columns: Column[];
  onRowClick?: (row: Row) => void;
  sorting: string | null;
  sortingOrder: 'asc' | 'desc';
  onChangeSorting: (column: Column, groupName?: string) => void;
  groupName?: string;
  folded?: boolean;
  onFoldGroup?: (groupName: string) => void;
}

const Content = ({
  data,
  columns,
  onRowClick,
  sorting,
  sortingOrder,
  onChangeSorting,
  groupName,
  folded,
  onFoldGroup,
}: Props) => {
  if (data.length === 0) return null;

  return (
    <>
      <thead>
        {groupName && (
          <tr>
            <GroupName css={{ gridColumnEnd: columns.length + 1 }}>
              <FoldTrigger onClick={() => onFoldGroup(groupName)}>
                {groupName} ({data.length})
              </FoldTrigger>
            </GroupName>
          </tr>
        )}
        {!folded && (
          <tr>
            {columns.map((column) => (
              <TH
                key={`th-${column.title}`}
                align={column.align}
                sortable={column.sortable}
                sorted={sorting === column.dataIndex}
                afterGroupName={!!groupName}
              >
                <span onClick={() => onChangeSorting(column, groupName)}>{column.title}</span>
              </TH>
            ))}
          </tr>
        )}
      </thead>
      {!folded && (
        <tbody>
          <For each={data}>
            {(row, index) => (
              <>
                <RowBlock key={`tr-${index}`} row={row} columns={columns} onRowClick={onRowClick} />
              </>
            )}
          </For>
        </tbody>
      )}
    </>
  );
};

export default Content;
```

Row.tsx
```
'use client';

import { block } from 'million/react';
import { Column, Row } from '@/types/table';
import Cell from './Cell';
import { TD } from './Content';
import { styled } from '@/stitches';

type Props = {
  row: Row;
  columns: Column[];
  onRowClick?: (row: Row) => void;
};

const RowBlock = block(({ row, columns, onRowClick }: Props) => {
  return (
    <TR clickable={!!onRowClick} onClick={() => (onRowClick ? onRowClick(row) : undefined)}>
      {columns.map((column) => (
        <Cell key={`td-${column.title}`} row={row} column={column} />
      ))}
    </TR>
  );
});

export default RowBlock;
```

and every component now have `"use client"` directive

**Comment by tobySolutions** [comment]
> So to be clear now, that's what I have at the moment:
> 
> package.json
> 
> ```
> {
>   "name": "frontend",
>   "version": "0.1.0",
>   "private": true,
>   "scripts": {
>     // default scripts
>   },
>   "dependencies": {
>     "@apollo/client": "^3.7.14",
>     "@auth0/nextjs-auth0": "^2.6.0",
>     // Radix stuff
>     "graphql": "^16.6.0",
>     "lodash": "^4.17.21",
>     "moment": "^2.29.4",
>     "million": "^2.4.8-beta.3",
>     "next": "13.4.3",
>     "next-images": "^1.8.5",
>     "react": "18.2.0",
>     "react-dom": "18.2.0",
>     "react-wrap-balancer": "^0.5.0"
>   },
>   "devDependencies": {
>     "@types/graphql": "14.5.0",
>     "@types/lodash": "^4.14.194",
>     "@types/moment": "^2.13.0",
>     "@types/node": "^20.2.3",
>     "@types/react": "^18.2.7",
>     "@types/react-dom": "^18.2.4",
>     "eslint": "8.41.0",
>     "eslint-config-next": "13.4.3",
>     "typescript": "5.0.4"
>   }
> }
> ```
> 
> next.config.mjs
> 
> ```
> import million from 'million/compiler';
> 
> /** @type {import('next').NextConfig} */
> const nextConfig = {
>   reactStrictMode: true,
> };
> 
> export default million.next(nextConfig);
> ```
> 
> TableContent.tsx
> 
> ```
> 'use client';
> 
> import { For } from 'million/react';
> import RowBlock from './Row';
> import { Column, Row } from '@/types/table';
> import { styled } from '@/stitches';
> 
> interface Props {
>   data: Row[];
>   columns: Column[];
>   onRowClick?: (row: Row) => void;
>   sorting: string | null;
>   sortingOrder: 'asc' | 'desc';
>   onChangeSorting: (column: Column, groupName?: string) => void;
>   groupName?: string;
>   folded?: boolean;
>   onFoldGroup?: (groupName: string) => void;
> }
> 
> const Content = ({
>   data,
>   columns,
>   onRowClick,
>   sorting,
>   sortingOrder,
>   onChangeSorting,
>   groupName,
>   folded,
>   onFoldGroup,
> }: Props) => {
>   if (data.length === 0) return null;
> 
>   return (
>     <>
>       <thead>
>         {groupName && (
>           <tr>
>             <GroupName css={{ gridColumnEnd: columns.length + 1 }}>
>               <FoldTrigger onClick={() => onFoldGroup(groupName)}>
>                 {groupName} ({data.length})
>               </FoldTrigger>
>             </GroupName>
>           </tr>
>         )}
>         {!folded && (
>           <tr>
>             {columns.map((column) => (
>               <TH
>                 key={`th-${column.title}`}
>                 align={column.align}
>                 sortable={column.sortable}
>                 sorted={sorting === column.dataIndex}
>                 afterGroupName={!!groupName}
>               >
>                 <span onClick={() => onChangeSorting(column, groupName)}>{column.title}</span>
>               </TH>
>             ))}
>           </tr>
>         )}
>       </thead>
>       {!folded && (
>         <tbody>
>           <For each={data}>
>             {(row, index) => (
>               <RowBlock key={`tr-${index}`} row={row} columns={columns} onRowClick={onRowClick} />
>             )}
>           </For>
>         </tbody>
>       )}
>     </>
>   );
> };
> 
> export default Content;
> ```
> 
> Row.tsx
> 
> ```
> 'use client';
> 
> import { block } from 'million/react';
> import { Column, Row } from '@/types/table';
> import Cell from './Cell';
> import { TD } from './Content';
> import { styled } from '@/stitches';
> 
> type Props = {
>   row: Row;
>   columns: Column[];
>   onRowClick?: (row: Row) => void;
> };
> 
> const RowBlock = block(({ row, columns, onRowClick }: Props) => {
>   return (
>     <TR clickable={!!onRowClick} onClick={() => (onRowClick ? onRowClick(row) : undefined)}>
>       {columns.map((column) => (
>         <Cell key={`td-${column.title}`} row={row} column={column} />
>       ))}
>     </TR>
>   );
> });
> 
> export default RowBlock;
> ```
> 
> and every component now have `"use client"` directive

Hey @enjoijkee, does it work now with what you have here?

**Comment by enjoijkee** [comment]
Hey @tobySolutions, no but @aidenybai is looking into this. We continue the discussion in the Discord thread (question "Can't get compiler working in Next.js"). I think Aiden or I will post an update here when the issue is resolved in some way.

**Comment by tobySolutions** [comment]
Hey @enjoijkee, I must have missed that somehow, thank you for this.

**Comment by rvuyyuru2** [comment]
import million from "million/compiler";
^^^^^^

SyntaxError: Cannot use import statement outside a module

**Comment by aidenybai** [comment]
@enjoijkee fixed in 2.4.8.

it will require one change on your part: you need to set `ssr={false}` on the For and have a second argument in the `block(..., { ssr: false})`
