### ISSUE TITLE
I get the error while implementing Million.js in next app "Error: See http://million.dev/docs/install to install the compiler." 

### ISSUE THREAD

**Issue by asad-xgrid** [aidenybai/million#508]
What ever i import error from million it generates compiler error
i have followed the installation instruction from the doc but still i can't succeed
next.config.mjs
![image](https://github.com/aidenybai/million/assets/102945740/f5f1b638-0126-446f-9e43-10a48fc4d365)

I have the following folder structure:
![image](https://github.com/aidenybai/million/assets/102945740/b2a808bd-1988-41ab-8f3d-6243957b7d09)

**Comment by aidenybai** [comment]
i don't believe you're using `auto: true`. We also released some bugfixes. Try `npm i million@latest`

**Comment by blackstorm** [comment]
I using `pnpm` got same error

**Comment by aberbinYesdevs** [comment]
Same erro here:

```
react-dom.development.js:10587 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at Object.throwInvalidHookError (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:10587:9)
    at useRef (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react/cjs/react.development.js:1765:21)
    at createChildren (webpack-internal:///(app-pages-browser)/./node_modules/million/dist/react.mjs:108:66)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/million/dist/react.mjs:93:27)
```

I'm using nextjs v.13 router version, this is a client site component. The block functionality is working but when I try to use <For> the code always return the error mentioned before.

Code:
```
export default function List() {
  const [items, setItems] = useState([1, 2, 3]);
 
  return (
    <div>
      <ul>
        <For each={items} memo>
          {(item) => <li>{item}</li>}
        </For>
      </ul>
    </div>
  );
```

**Comment by jwilbur-godaddy** [comment]
I dug through the code of million and found that this is where the error is happening for me:

```javascript
if (typeof window === "undefined") {
  throw new Error(
    "See http://million.dev/docs/install to install the compiler."
  );
}
```

Pretty unambiguous what causes that error to be thrown. But what would cause `window` to be undefined? It seems like a server-side rendering thing, but AFAIK, we are not using SSR. Is there any workaround for this?

Even if we are using SSR, is there anything we can do to avoid this issue? I have tried way too many workarounds with no success.

**Comment by renhiyama** [comment]
> I dug through the code of million and found that this is where the error is happening for me:
> 
> ```js
> if (typeof window === "undefined") {
>   throw new Error(
>     "See http://million.dev/docs/install to install the compiler."
>   );
> }
> ```
> 
> Pretty unambiguous what causes that error to be thrown. But what would cause `window` to be undefined? It seems like a server-side rendering thing, but AFAIK, we are not using SSR. Is there any workaround for this?
> 
> Even if we are using SSR, is there anything we can do to avoid this issue? I have tried way too many workarounds with no success.

by default, `million/react` is transformed to `million/react-server` by million compiler itself. On the browser side, you still get to see `million/react` as expected. So as expected, if `window` is undefined, that means its probably running at serverside, which means the compiler didnt run/didnt replace the code. That's why it's asking to install the compiler properly. @aidenybai I suggest different checking, as Deno has `window` available, still being server sided runtime. Consider adding an additional check for `globalThis.Deno==undefined` or similar.

**Comment by ningo-agilityio** [comment]
I faced this issue few days agos. You need to ensure that you use **For** and **block** correctly in React component, not in Astro component.
And directive `client:only="react"` need to be used to load this React component. You can check my below snippet code:

**PostItem.tsx**
```
import React from 'react';
import { For } from 'million/react';
import type { MetaPostProps } from '../types/meta'

const PostItem = ({ data }: { data: MetaPostProps[] }) => (
  <For each={data}>{(post: MetaPostProps) => {
    const  { body = ''} = post
    return (
      <li class="rounded-md bg-white shadow-md transition hover:shadow-xl">
        {body}
      </li>
    )}}
  </For>
)
export default PostItem
```

**PostBody.tsx**
```
import React from 'react'
import ReactMarkdown from 'react-markdown'
import { block } from 'million/react';

const PostBody: React.FC<{ content: string }> = ({ content }) => {
  return (
    <div>{content}</div>
  )
}
export default block(PostBody)

```
